version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns: ["*"]
        update-type: ["version-update:semver-minor", "version-update:semver-patch"]  # Skip majors
